version: '3'
volumes:
  postgres_data:
      driver: local
services:
  back:
    container_name: back
    build: ./back
    ports:
      - '8081:8081'
    env_file:
      ./backend.env
    depends_on:
      - postgres
      - keycloak
  front:
    container_name: front
    build: ./front
    ports:
      - '80:80'
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
      - 5432:5432
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      volumes:
        - $PWD/keys:/opt/keycloak/conf
      env_file:
        ./keycloak.env
      ports:
        - 8443:8443
      depends_on:
        - postgres
