version: '3'
volumes:
  postgres_data:
      driver: local
services:
  back:
    container_name: back
    hostname: backend
    build: ./back
    ports:
      - '8081:8081'
    env_file:
      ./backend.env
    depends_on:
      - postgres
      - keycloak
  front:
    container_name: front
    build: ./front
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    hostname: keycloak
    volumes:
      - /etc/letsencrypt:/cert
    env_file:
      ./keycloak.env
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres