version: '3'
volumes:
  postgres_data:
    driver: local
services:
  back:
    container_name: back
    hostname: backend
    build: ./back
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '8081:8081'
    env_file:
      ./backend.env
    depends_on:
      - postgres
      - keycloak
  front:
    container_name: front
    build: ./front
    ports:
      - 80:80
    depends_on:
      - back
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    hostname: keycloak
    env_file:
      ./keycloak.env
    ports:
      - 8443:8443
    depends_on:
      - postgres
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=cyril.bernadet@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`bernadet.ddns.net`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"