version: '3'
volumes:
  postgres_data:
    driver: local
services:
  back:
    container_name: back
    hostname: backend
    build: ./back
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    expose:
      - 8081
    env_file:
      ./backend.env
    depends_on:
      - postgres
      - keycloak
    networks:
    - bernadet-network
  front:
    container_name: front
    build: ./front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`bernadet.ddns.net`)"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
    expose:
      - 8080
    depends_on:
      - back
    networks:
    - bernadet-network
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    networks:
    - bernadet-network
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    hostname: keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.routers.keycloak.middlewares=redirect-middleware"
    env_file:
      ./keycloak.env    
    expose:
      - 8080
      - 9990
    depends_on:
      - postgres
    networks:
    - bernadet-network
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
    - bernadet-network
networks:
  bernadet-network: